language: python
python:
    - "3.6"
install: "python setup.py install"
script: "python setup.py test -a '--cov=illume'"
before_install:
    - sudo apt-get install python3-dev
after_success:
    - codecov
